### PR TITLE
reorder again

### PR DESCRIPTION
**Pull request by vmario89**

### CODE REVIEW

**Comment by vmario89** [comment]
some config settings where not taken over from /etc/config-site.php because the initial file overwrites again

**Review by jsuto — CHANGES_REQUESTED** [review]
I don't think it's a good idea to move this huge block of config above where config-site.php is read, because if PATH_PREFIX is overridden, then it won't be effective.

**Comment by vmario89** [comment]
i have PATH_PREFIX='/' and the config-site.php is not read this way. Means the changed i applied in /etc/config-site.php do never apply because this config overrides it. I think thats not the wanted behaviour

**Review by jsuto — COMMENTED** [review]
The PATH_PREFIX is set in the 29th line. Let's say a user wants to change it, and overrides it in config-site.php. The problem is that with your change it can't be done any longer, because you move several settings before reading values from config-site.php.

**Comment by vmario89** [comment]
okay, but how to deal with customizations in custom-settings.php for the BRANDING_* settings then? the only way i have right now is changing the settings directory in /var/piler/www/config.php

**Comment by jsuto** [comment]
Ehh, you are right, I see your point now. This is the catch 22. You need to defer all PATH_PREFIX related values until you read PATH_PREFIX from config-site.php, however after that you can't override them. I think I'll revert my original PR, and document it that if you changed PATH_PREFIX, then you need to fix BRANDING_*, etc. variables that depend on it. Give me a little time to think about it. @th-2021 what do you think?

**Comment by jsuto** [comment]
I think we can leave both JS_CODE and CSS_CODE as where they are now, because it's unlikely that you want to override them.

We need to move up the following:
- BRANDING_FAVICON perhaps without $config['PATH_PREFIX']
- SITE_LOGO_LG
- SITE_LOGO_SM
- all the BRANDING_* variables

However, I'd rather leave these below after we read config-site.php, unless you want to customize them as well:

- $config['ICON_DOC'] = $config['PATH_PREFIX'] . 'assets/images/fileicons/doc.png';
- $config['ICON_XLS'] = $config['PATH_PREFIX'] . 'assets/images/fileicons/xls.png';
- $config['ICON_PDF'] = $config['PATH_PREFIX'] . 'assets/images/fileicons/pdf.png';
- $config['ICON_IMAGE'] = $config['PATH_PREFIX'] . 'assets/images/fileicons/image.png';
- $config['ICON_FILE'] = $config['PATH_PREFIX'] . 'assets/images/fileicons/file.png';

**Comment by th-2021** [comment]
Would it be an option to introduce customization variables that give
combined with path_prefix the $config variable?

E.g.

config.php.in:

$cust['ICON_FILE'] = 'assets/images/fileicons/file.png'

config-site.php:
$cust['ICON_FILE'] = 'assets/images/fileicons/myfile.png

Behind inclusion of config-site.php:
$config['ICON_FILE'] = $config['PATH_PREFIX'] . $cust['ICON_FILE']

Am 22.08.2024 um 19:17 schrieb jsuto:

**Comment by th-2021** [comment]
E.g. something like:
diff --git a/config.php.in b/config.php.in
index 7dd50f96..d12cebf0 100644
--- a/config.php.in
+++ b/config.php.in
@@ -354,6 +354,14 @@ $letters = array('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M'

 define('NOW', time());

+$config['SITE_LOGO_LG'] = 'assets/images/archive-logo-lg.png';
+$config['SITE_LOGO_SM'] = 'assets/images/archive-logo-sm.png';
+
+$config['ICON_DOC'] = 'assets/images/fileicons/doc.png';
+$config['ICON_XLS'] = 'assets/images/fileicons/xls.png';
+$config['ICON_PDF'] = 'assets/images/fileicons/pdf.png';
+$config['ICON_IMAGE'] = 'assets/images/fileicons/image.png';
+$config['ICON_FILE'] = 'assets/images/fileicons/file.png';

 /*
  * normally you don't have to change anything below
@@ -389,24 +397,24 @@ $config['CSS_CODE'] = '
    <link rel="stylesheet" href="' . $config['PATH_PREFIX'] . 'assets/css/piler.css" />
 ';

-
-$config['BRANDING_FAVICON'] = '
+if (!isset($config['BRANDING_FAVICON']))
+  $config['BRANDING_FAVICON'] = '
   
   <link rel="apple-touch-icon-precomposed" sizes="144x144" href="' . $config['PATH_PREFIX'] . 'assets/ico/apple-touch-icon-144-precomposed.png">
   <link rel="apple-touch-icon-precomposed" sizes="114x114" href="' . $config['PATH_PREFIX'] . 'assets/ico/apple-touch-icon-114-precomposed.png">
   <link rel="apple-touch-icon-precomposed" sizes="72x72" href="' . $config['PATH_PREFIX'] . 'assets/ico/apple-touch-icon-72-precomposed.png">
   <link rel="apple-touch-icon-precomposed" href="' . $config['PATH_PREFIX'] . 'assets/ico/apple-touch-icon-57-precomposed.png">
   <link rel="shortcut icon" href="' . $config['PATH_PREFIX'] . 'assets/ico/favicon.png">
-';
+  ';

-$config['SITE_LOGO_LG'] = $config['PATH_PREFIX'] . 'assets/images/archive-logo-lg.png';
-$config['SITE_LOGO_SM'] = $config['PATH_PREFIX'] . 'assets/images/archive-logo-sm.png';
+$config['SITE_LOGO_LG'] = $config['PATH_PREFIX'] . $config['SITE_LOGO_LG'];
+$config['SITE_LOGO_SM'] = $config['PATH_PREFIX'] . $config['SITE_LOGO_SM'];

-$config['ICON_DOC'] = $config['PATH_PREFIX'] . 'assets/images/fileicons/doc.png';
-$config['ICON_XLS'] = $config['PATH_PREFIX'] . 'assets/images/fileicons/xls.png';
-$config['ICON_PDF'] = $config['PATH_PREFIX'] . 'assets/images/fileicons/pdf.png';
-$config['ICON_IMAGE'] = $config['PATH_PREFIX'] . 'assets/images/fileicons/image.png';
-$config['ICON_FILE'] = $config['PATH_PREFIX'] . 'assets/images/fileicons/file.png';
+$config['ICON_DOC'] = $config['PATH_PREFIX'] . $config['ICON_DOC'];
+$config['ICON_XLS'] = $config['PATH_PREFIX'] . $config['ICON_XLS'];
+$config['ICON_PDF'] = $config['PATH_PREFIX'] . $config['ICON_PDF'];
+$config['ICON_IMAGE'] = $config['PATH_PREFIX'] . $config['ICON_IMAGE'];
+$config['ICON_FILE'] = $config['PATH_PREFIX'] . $config['ICON_FILE'];

 foreach ($config as $k => $v) {
    define($k, $v);

**Comment by th-2021** [comment]
#203 will work, but branding stuff has to be duplicated just for prefix change. A solution which allows changing just the prefix would imho be better.

**Comment by jsuto** [comment]
Closed in favour of #203

**Pull request closed without merging**
